### ISSUE TITLE
Орфографическая ошибка 

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO20_Operation_Pink_Citadel.abramia#2]
https://github.com/rempopo/CO20_Operation_Pink_Citadel.abramia/blob/79628b46a070e5e88cb4818518a6a35caaa13289/dzn_tSFramework/Modules/MissionConditions/Endings.hpp#L7

**Comment by 10Dozen** [comment]
Fixed at https://github.com/rempopo/CO20_Operation_Pink_Citadel.abramia/commit/544822cf075eaefc73c64b999792d444ca144bf3 https://github.com/rempopo/CO20_Operation_Pink_Citadel.abramia/blob/544822cf075eaefc73c64b999792d444ca144bf3/dzn_tSFramework/Modules/MissionConditions/Endings.hpp#L7
